Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Models/ErrorViewModel.cs
namespace MVCAssignmentProject.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCAssignmentProject.Controllers;

public class AccountController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCAssignmentProject.Controllers;

public class AdminController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Controllers/CastController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCAssignmentProject.Controllers;

public class CastController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Controllers/GenreController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Models.RequestModel;
using Microsoft.AspNetCore.Mvc;

namespace MVCAssignmentProject.Controllers;

public class GenreController : Controller
{
    private readonly IGenreService _service;

    public GenreController(IGenreService service)
    {
        _service = service;
    }
    // GET
    public IActionResult Index()
    {
        var genres = _service.GetAllGenres();
        return View(genres);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(GenreRequestModel model)
    {
        if (ModelState.IsValid)
        {
            _service.AddGenre(model);
            return RedirectToAction("Index");
        }

        return View(model);
    }
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCAssignmentProject.Models;

namespace MVCAssignmentProject.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Controllers/MovieController.cs
using System.Diagnostics;
using ApplicationCore.Contracts.Services;
using ApplicationCore.Entities;
using ApplicationCore.Models.RequestModel;
using ApplicationCore.Models.ResponseModel;
using Infrastructure.Repository;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace MVCAssignmentProject.Controllers;

public class MovieController : Controller
{
    private readonly IMovieService _service;
    private readonly IGenreService _genreService;
    private int GenreId; 

    public MovieController(IMovieService service, IGenreService genreService)
    {
        _service = service;
        _genreService = genreService;
    }
    // GET
    public IActionResult Index()
    {
        var movies = _service.GetAllMovies();
        var result = _genreService.GetAllGenres().Select(x => new { Key = x.Id, Value = x.Name });
        ViewBag.GenresList = new SelectList(result, "Key", "Value");
        return View(movies);
    }
    [HttpGet]
    public IActionResult Create(){
    
        return View();
    }

    [HttpPost]
    public IActionResult Create(MovieRequestModel model)
    {
        if (ModelState.IsValid)
        {
            _service.AddMovie(model);
            return RedirectToAction("Index");
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult Edit(int movieId)
    {
        var model = _service.GetMovie(movieId);
        return View(model);
    }

    [HttpPost]
    public IActionResult Edit(MovieResponseModel model)
    {
        if (ModelState.IsValid)
        {
            MovieRequestModel movie = new MovieRequestModel();
            movie.Budget = model.Budget;
            movie.Title = model.Title;
            movie.Overview = model.Overview;
            movie.Price = model.Price;
            movie.Revenue = model.Revenue;
            movie.BackdropUrl = model.BackdropUrl;
            movie.ImdbUrl = model.ImdbUrl;
            movie.OriginalLanguage = model.OriginalLanguage;
            movie.PosterUrl = model.PosterUrl;
            movie.RunTime = model.RunTime;
            movie.TagLine = model.TagLine;
            _service.UpdateMovie(movie, model.Id);
            return RedirectToAction("Index");
        }
        return View(model);
    }

    [HttpGet]
    public IActionResult Delete(int movieId)
    {
        var result = _service.GetMovie(movieId);
        return View(result);
    }

    [HttpPost]
    public IActionResult Delete(MovieResponseModel model)
    {
        _service.DeleteMovie(model.Id);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult GrosserFilter()
    {
        var movies = _service.GetHighestGrossingMovies();
        // ViewBag["movies"] = movies;
        return View("index", movies);
    }

    [HttpGet]
    public IActionResult Genre()
    {
        return RedirectToAction("Index", "Genre", "Index");
    }

    [HttpPost]
    public IActionResult MoviesByGenre(int GenreId)
    {
        var movies = _service.GetMoviesByGenre(GenreId);
        return View("index", movies);
    }

    [HttpGet]
    public IActionResult MovieDetail(int movieId)
    {
        var movie = _service.GetMovie(movieId);
        return View();
    }
    
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCAssignmentProject.Controllers;

public class UserController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Genre/Create.cshtml
@model GenreRequestModel
<form asp-action="Create" asp-controller="Genre">
    <div class="my-3">
        <label>Enter a Genre</label>
        <input type="text" name="Name" placeholder="Enter Genre Title" class="form-control"/>
    </div>
    <input type="submit" value="Save" class="btn-primary btn"/>
</form>

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Genre/Index.cshtml
@model IEnumerable<GenreResponseModel>

<h2>Genres List</h2>
    <a class="border border-primary m-2 rounded-circle" asp-action="Create" asp-controller="Genre">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-file-plus-fill text-primary m-2" viewBox="0 0 16 16">
            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2M8.5 6v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 1 0"/>
        </svg>
    </a>
<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Genre</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
        </tr>
    }
    </tbody>
</table>

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Movie/Create.cshtml
@model MovieRequestModel

<form asp-action="Create" asp-controller="Movie">
    <div class="my-3">
        <label>Enter Movie Title</label>
        <input type="text" name="Title" placeholder="Enter Movie Title" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter BackDropUrl</label>
        <input type="text" name="BackdropUrl" placeholder="Enter BackDrop Url" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter Movie Budget</label>
        <input type="text" name="Budget" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter Movie ImdbUrl</label>
        <input type="text" name="ImdbUrl" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter Movie Original Language</label>
        <input type="text" name="OriginalLanguage" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter Movie Overview</label>
        <input type="text" name="Overview" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter PosterUrl</label>
        <input type="text" name="PosterUrl" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter Price</label>
        <input type="text" name="Price" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter Revenue</label>
        <input type="text" name="Revenue" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter RunTime</label>
        <input type="text" name="RunTime" class="form-control"/>
    </div>
    <div class="my-3">
        <label>Enter TagLine</label>
        <input type="text" name="TagLine" class="form-control"/>
    </div>    
    <div class="my-3">
        <label>Enter TmdbUrl</label>
        <input type="text" name="TmdbUrl" class="form-control"/>
    </div>
    <input type="submit" value="Save" class="btn-primary btn"/>
</form>

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Movie/Delete.cshtml
@model MovieResponseModel

@if (Model != null)
{
    <form asp-action="Delete" asp-controller="Movie" asp-route-movieId="@Model.Id">
        <h3>Do you want to delete the following Movie?</h3>
        <div class="my-3">
            <label> Name = </label>@Model.Title
        </div>
        <input type="hidden" name="Id" value="@Model.Id" />
        <button class="btn btn-danger">Delete</button>
    </form>
}
else
{
    <h3>Movie Not Found</h3>
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Movie/Edit.cshtml
@model MovieResponseModel

<h2>Edit Your Movie Details</h2>
@if (Model != null)
{
    <form asp-action="Edit" asp-controller="Movie">
        <input type="hidden" name="Id" value="@Model.Id"/>
        <div class="my-3">
            <label>Enter Movie  Title</label>
            <input type="text" name="Title" value="@Model.Title" placeholder="Enter Movie Title" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter BackDropUrl</label>
            <input type="text" name="BackdropUrl" value="@Model.BackdropUrl" placeholder="Enter BackDrop Url" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter Movie Budget</label>
            <input type="text" name="Budget" value="@Model.Budget" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter Movie ImdbUrl</label>
            <input type="text" name="ImdbUrl" value="@Model.ImdbUrl" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter Movie Original Language</label>
            <input type="text" name="OriginalLanguage" value="@Model.OriginalLanguage" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter Movie Overview</label>
            <input type="text" name="Overview" value="@Model.Overview" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter PosterUrl</label>
            <input type="text" name="PosterUrl" value="@Model.PosterUrl" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter Price</label>
            <input type="text" name="Price" value="@Model.Price" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter Revenue</label>
            <input type="text" name="Revenue" value="@Model.Revenue" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter RunTime</label>
            <input type="text" name="RunTime" value="@Model.RunTime" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter TagLine</label>
            <input type="text" name="TagLine" value="@Model.TagLine" class="form-control"/>
        </div>
        <div class="my-3">
            <label>Enter TmdbUrl</label>
            <input type="text" name="TmdbUrl" value="@Model.ImdbUrl" class="form-control"/>
        </div>
        <input type="submit" value="Update" class="btn-primary btn"/>
    </form>
}
else
{
    <h3>No Movie Found</h3>
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Movie/MovieDetail.cshtml
@model ApplicationCore.Entities.Movie
    <div class="container mt-5">
        <!-- First Row -->
        <div class="row">
            <!-- First Column: Movie Poster -->
            <div class="col-md-4">
                <img src="movie-poster.jpg" class="img-fluid" alt="Movie Poster">
            </div>
            <!-- Second Column: Movie Details -->
            <div class="col-md-4">
                <h2>Movie Title</h2>
                <p><span class="badge badge-primary">Genre 1</span> <span class="badge badge-secondary">Genre 2</span></p>
                <p>Rating: <span class="badge badge-success">8.5</span></p>
                <p>Overview: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet accumsan tortor.</p>
            </div>
            <!-- Third Column: Buttons -->
            <div class="col-md-4">
                <button class="btn btn-primary mb-2" data-toggle="modal" data-target="#buyMovieModal">Buy Movie</button>
                <button class="btn btn-secondary" data-toggle="modal" data-target="#reviewModal">Review</button>
            </div>
        </div>

        <!-- Second Row -->
        <div class="row mt-4">
            <!-- First Column: Movie Facts and Trailers -->
            <div class="col-md-6">
                <h3>Movie Facts</h3>
                <ul class="list-group mb-3">
                    <li class="list-group-item">Fact 1</li>
                    <li class="list-group-item">Fact 2</li>
                    <li class="list-group-item">Fact 3</li>
                </ul>
                <h3>Trailers</h3>
                <ul class="list-group">
                    <li class="list-group-item">Trailer 1</li>
                    <li class="list-group-item">Trailer 2</li>
                </ul>
            </div>
            <!-- Second Column: Casts -->
            <div class="col-md-6">
                <h3>Casts</h3>
                <ul class="list-group">
                    <li class="list-group-item"><a href="cast-details.html">Cast 1</a></li>
                    <li class="list-group-item"><a href="cast-details.html">Cast 2</a></li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Buy Movie Modal -->
    <div class="modal fade" id="buyMovieModal" tabindex="-1" role="dialog" aria-labelledby="buyMovieModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="buyMovieModalLabel">Buy Movie</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Price: $19.99</p>
                    <button class="btn btn-success">Purchase</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Review Modal -->
    <div class="modal fade" id="reviewModal" tabindex="-1" role="dialog" aria-labelledby="reviewModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="reviewModalLabel">Review</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="rating">Rating</label>
                        <select class="form-control" id="rating">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                            <option>9</option>
                            <option>10</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="review">Review</label>
                        <textarea class="form-control" id="review" rows="3"></textarea>
                    </div>
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Movie/index.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model IEnumerable<MovieResponseModel>

<div class="d-flex">
    <h1>Movies List</h1>
    <a class="border border-primary m-2 rounded-circle" asp-action="Create" asp-controller="Movie">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-file-plus-fill text-primary m-2" viewBox="0 0 16 16">
            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2M8.5 6v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 1 0"/>
        </svg>
    </a>
        <select onchange="MoviesByGenre(this.value)" asp-items="ViewBag.GenresList">
            <option value="0">Select</option>
        </select>
    <a class="m-2 my-3" asp-action="GrosserFilter" asp-controller="Movie">
        Highest Grossing Movies
    </a>
    <a class="m-2 my-3" asp-action="Genre" asp-controller="Movie">
        Genre
    </a>
</div>
@if (Model != null)
{
    <div class="row row-cols-1 row-cols-md-4 g-4">
        @foreach (var item in Model)
        {
            <a asp-action="">
                <partial name="_MovieCard" model="item"/>
            </a>
        }
    </div>
}
else
{
    <h3>No Movies to show</h3>
}

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MVCAssignmentProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MVCAssignmentProject.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCAssignmentProject</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - MVCAssignmentProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Week4 - MVC/MVCAssignmentProject/MVCAssignmentProject/Views/Shared/_MovieCard.cshtml
@model MovieResponseModel
@if (Model != null)
{
    <div class="col">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top rounded-1" src="@Model.BackdropUrl" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text text-truncate">@Model.Overview</p>
                <p class="card-text"><small class="text-muted">Release on @Model.ReleaseDate </small></p>
            </div>
            <div>
                <a class="float-start border border-danger m-2 rounded-circle" asp-action="Delete" asp-controller="Movie" asp-route-movieId="@Model.Id">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill text-danger m-2" viewBox="0 0 16 16">
                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                    </svg>
                </a>
                <a class="float-end border border-warning m-2 rounded-circle" asp-action="Edit" asp-controller="Movie" asp-route-movieId="@Model.Id">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill text-warning m-2" viewBox="0 0 16 16">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                    </svg>
                </a>

            </div>
        </div>
    </div>
}
else
{
    <h2>Card not available</h2>
}